// Code generated by protoc-gen-go. DO NOT EDIT.
// source: map_service.proto

package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PointRequest
type PointRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointRequest) Reset()         { *m = PointRequest{} }
func (m *PointRequest) String() string { return proto.CompactTextString(m) }
func (*PointRequest) ProtoMessage()    {}
func (*PointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_service_b42a29a5331fb92f, []int{0}
}
func (m *PointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointRequest.Unmarshal(m, b)
}
func (m *PointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointRequest.Marshal(b, m, deterministic)
}
func (dst *PointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointRequest.Merge(dst, src)
}
func (m *PointRequest) XXX_Size() int {
	return xxx_messageInfo_PointRequest.Size(m)
}
func (m *PointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointRequest proto.InternalMessageInfo

// Points are represented as latitude-longitude pairs and counts
type Point struct {
	Latitude             string   `protobuf:"bytes,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_service_b42a29a5331fb92f, []int{1}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Point) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Point) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*PointRequest)(nil), "services.PointRequest")
	proto.RegisterType((*Point)(nil), "services.Point")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MapServiceClient is the client API for MapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MapServiceClient interface {
	// A server-to-client streaming RPC.
	//
	// Streams all IPv6 data points
	List(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (MapService_ListClient, error)
}

type mapServiceClient struct {
	cc *grpc.ClientConn
}

func NewMapServiceClient(cc *grpc.ClientConn) MapServiceClient {
	return &mapServiceClient{cc}
}

func (c *mapServiceClient) List(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (MapService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MapService_serviceDesc.Streams[0], "/services.MapService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &mapServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MapService_ListClient interface {
	Recv() (*Point, error)
	grpc.ClientStream
}

type mapServiceListClient struct {
	grpc.ClientStream
}

func (x *mapServiceListClient) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MapServiceServer is the server API for MapService service.
type MapServiceServer interface {
	// A server-to-client streaming RPC.
	//
	// Streams all IPv6 data points
	List(*PointRequest, MapService_ListServer) error
}

func RegisterMapServiceServer(s *grpc.Server, srv MapServiceServer) {
	s.RegisterService(&_MapService_serviceDesc, srv)
}

func _MapService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PointRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MapServiceServer).List(m, &mapServiceListServer{stream})
}

type MapService_ListServer interface {
	Send(*Point) error
	grpc.ServerStream
}

type mapServiceListServer struct {
	grpc.ServerStream
}

func (x *mapServiceListServer) Send(m *Point) error {
	return x.ServerStream.SendMsg(m)
}

var _MapService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.MapService",
	HandlerType: (*MapServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _MapService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "map_service.proto",
}

func init() { proto.RegisterFile("map_service.proto", fileDescriptor_map_service_b42a29a5331fb92f) }

var fileDescriptor_map_service_b42a29a5331fb92f = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0x2c, 0x88,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80,
	0x72, 0x8b, 0x95, 0xf8, 0xb8, 0x78, 0x02, 0xf2, 0x33, 0xf3, 0x4a, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x94, 0xc2, 0xb9, 0x58, 0xc1, 0x7c, 0x21, 0x29, 0x2e, 0x8e, 0x9c, 0xc4, 0x92, 0xcc,
	0x92, 0xd2, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x86, 0x8b,
	0x33, 0x27, 0x3f, 0x2f, 0x1d, 0x22, 0xc9, 0x04, 0x96, 0x44, 0x08, 0x08, 0x89, 0x70, 0xb1, 0x26,
	0xe7, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x38, 0x46, 0x8e, 0x5c,
	0x5c, 0xbe, 0x89, 0x05, 0xc1, 0x10, 0x7b, 0x85, 0x8c, 0xb9, 0x58, 0x7c, 0x32, 0x8b, 0x4b, 0x84,
	0xc4, 0xf4, 0x60, 0x2e, 0xd1, 0x43, 0x76, 0x86, 0x14, 0x3f, 0x9a, 0xb8, 0x12, 0x83, 0x01, 0x63,
	0x12, 0x1b, 0xd8, 0xf1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xef, 0x50, 0xc5, 0xd1,
	0x00, 0x00, 0x00,
}
