// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/map_service.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Points are represented as latitude-longitude pairs and counts
type Point struct {
	Latitude             string   `protobuf:"bytes,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_service_5d422286e601c9f5, []int{0}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Point) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *Point) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// PointRequest
type PointRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointRequest) Reset()         { *m = PointRequest{} }
func (m *PointRequest) String() string { return proto.CompactTextString(m) }
func (*PointRequest) ProtoMessage()    {}
func (*PointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_service_5d422286e601c9f5, []int{1}
}
func (m *PointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointRequest.Unmarshal(m, b)
}
func (m *PointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointRequest.Marshal(b, m, deterministic)
}
func (dst *PointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointRequest.Merge(dst, src)
}
func (m *PointRequest) XXX_Size() int {
	return xxx_messageInfo_PointRequest.Size(m)
}
func (m *PointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointRequest proto.InternalMessageInfo

// BoundedPointsRequest
type BoundedPointsRequest struct {
	LatMin               string   `protobuf:"bytes,1,opt,name=latMin,proto3" json:"latMin,omitempty"`
	LatMax               string   `protobuf:"bytes,2,opt,name=latMax,proto3" json:"latMax,omitempty"`
	LongMin              string   `protobuf:"bytes,3,opt,name=longMin,proto3" json:"longMin,omitempty"`
	LongMax              string   `protobuf:"bytes,4,opt,name=longMax,proto3" json:"longMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoundedPointsRequest) Reset()         { *m = BoundedPointsRequest{} }
func (m *BoundedPointsRequest) String() string { return proto.CompactTextString(m) }
func (*BoundedPointsRequest) ProtoMessage()    {}
func (*BoundedPointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_service_5d422286e601c9f5, []int{2}
}
func (m *BoundedPointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoundedPointsRequest.Unmarshal(m, b)
}
func (m *BoundedPointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoundedPointsRequest.Marshal(b, m, deterministic)
}
func (dst *BoundedPointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoundedPointsRequest.Merge(dst, src)
}
func (m *BoundedPointsRequest) XXX_Size() int {
	return xxx_messageInfo_BoundedPointsRequest.Size(m)
}
func (m *BoundedPointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoundedPointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoundedPointsRequest proto.InternalMessageInfo

func (m *BoundedPointsRequest) GetLatMin() string {
	if m != nil {
		return m.LatMin
	}
	return ""
}

func (m *BoundedPointsRequest) GetLatMax() string {
	if m != nil {
		return m.LatMax
	}
	return ""
}

func (m *BoundedPointsRequest) GetLongMin() string {
	if m != nil {
		return m.LongMin
	}
	return ""
}

func (m *BoundedPointsRequest) GetLongMax() string {
	if m != nil {
		return m.LongMax
	}
	return ""
}

// PointsResponse contains points for the client
type PointsResponse struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointsResponse) Reset()         { *m = PointsResponse{} }
func (m *PointsResponse) String() string { return proto.CompactTextString(m) }
func (*PointsResponse) ProtoMessage()    {}
func (*PointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_map_service_5d422286e601c9f5, []int{3}
}
func (m *PointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointsResponse.Unmarshal(m, b)
}
func (m *PointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointsResponse.Marshal(b, m, deterministic)
}
func (dst *PointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointsResponse.Merge(dst, src)
}
func (m *PointsResponse) XXX_Size() int {
	return xxx_messageInfo_PointsResponse.Size(m)
}
func (m *PointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointsResponse proto.InternalMessageInfo

func (m *PointsResponse) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "proto.Point")
	proto.RegisterType((*PointRequest)(nil), "proto.PointRequest")
	proto.RegisterType((*BoundedPointsRequest)(nil), "proto.BoundedPointsRequest")
	proto.RegisterType((*PointsResponse)(nil), "proto.PointsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MapServiceClient is the client API for MapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MapServiceClient interface {
	// Streams all IPv6 data points
	AllPoints(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointsResponse, error)
	// Streams Points bounded by coordinates
	BoundedPoints(ctx context.Context, in *BoundedPointsRequest, opts ...grpc.CallOption) (*PointsResponse, error)
}

type mapServiceClient struct {
	cc *grpc.ClientConn
}

func NewMapServiceClient(cc *grpc.ClientConn) MapServiceClient {
	return &mapServiceClient{cc}
}

func (c *mapServiceClient) AllPoints(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointsResponse, error) {
	out := new(PointsResponse)
	err := c.cc.Invoke(ctx, "/proto.MapService/AllPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapServiceClient) BoundedPoints(ctx context.Context, in *BoundedPointsRequest, opts ...grpc.CallOption) (*PointsResponse, error) {
	out := new(PointsResponse)
	err := c.cc.Invoke(ctx, "/proto.MapService/BoundedPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapServiceServer is the server API for MapService service.
type MapServiceServer interface {
	// Streams all IPv6 data points
	AllPoints(context.Context, *PointRequest) (*PointsResponse, error)
	// Streams Points bounded by coordinates
	BoundedPoints(context.Context, *BoundedPointsRequest) (*PointsResponse, error)
}

func RegisterMapServiceServer(s *grpc.Server, srv MapServiceServer) {
	s.RegisterService(&_MapService_serviceDesc, srv)
}

func _MapService_AllPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceServer).AllPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MapService/AllPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceServer).AllPoints(ctx, req.(*PointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapService_BoundedPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoundedPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServiceServer).BoundedPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MapService/BoundedPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServiceServer).BoundedPoints(ctx, req.(*BoundedPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MapService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MapService",
	HandlerType: (*MapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllPoints",
			Handler:    _MapService_AllPoints_Handler,
		},
		{
			MethodName: "BoundedPoints",
			Handler:    _MapService_BoundedPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/map_service.proto",
}

func init() {
	proto.RegisterFile("proto/map_service.proto", fileDescriptor_map_service_5d422286e601c9f5)
}

var fileDescriptor_map_service_5d422286e601c9f5 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xff, 0xf9, 0xd7, 0x56, 0x3b, 0xee, 0xee, 0x61, 0x5c, 0x35, 0xac, 0x1e, 0x4a, 0xf0,
	0xd0, 0xd3, 0x0a, 0x2b, 0x08, 0x1e, 0x15, 0x3c, 0x2e, 0x48, 0x3d, 0x78, 0x94, 0xb8, 0x0d, 0x52,
	0x88, 0x49, 0xdc, 0xa4, 0x52, 0xfc, 0x10, 0x7e, 0x66, 0xd9, 0x24, 0xad, 0xbb, 0xa0, 0xa7, 0xf2,
	0x7e, 0xaf, 0x33, 0x2f, 0xf3, 0xe0, 0xd4, 0xac, 0xb5, 0xd3, 0x97, 0x6f, 0xdc, 0x3c, 0x5b, 0xb1,
	0xfe, 0x68, 0x56, 0x62, 0xee, 0x09, 0xa6, 0xfe, 0xc3, 0x9e, 0x20, 0x7d, 0xd0, 0x8d, 0x72, 0x38,
	0x83, 0x03, 0xc9, 0x5d, 0xe3, 0xda, 0x5a, 0x50, 0x52, 0x90, 0x32, 0xaf, 0x06, 0x8d, 0xe7, 0x90,
	0x4b, 0xad, 0x5e, 0x83, 0xf9, 0xdf, 0x9b, 0x3f, 0x00, 0xa7, 0x90, 0xae, 0x74, 0xab, 0x1c, 0x4d,
	0x0a, 0x52, 0x8e, 0xab, 0x20, 0xd8, 0x04, 0x46, 0x7e, 0x71, 0x25, 0xde, 0x5b, 0x61, 0x1d, 0xfb,
	0x84, 0xe9, 0x9d, 0x6e, 0x55, 0x2d, 0x6a, 0x8f, 0x6d, 0xe4, 0x78, 0x02, 0x99, 0xe4, 0x6e, 0xd9,
	0xa8, 0x98, 0x1a, 0x55, 0xcf, 0x79, 0x17, 0x03, 0xa3, 0x42, 0x0a, 0xfb, 0x9b, 0xe8, 0xcd, 0x40,
	0xe2, 0x8d, 0x5e, 0x0e, 0x0e, 0xef, 0xe8, 0xde, 0x96, 0xc3, 0x3b, 0x76, 0x0d, 0x93, 0x3e, 0xd4,
	0x1a, 0xad, 0xac, 0xc0, 0x0b, 0xc8, 0x8c, 0x27, 0x94, 0x14, 0x49, 0x79, 0xb8, 0x18, 0x85, 0x56,
	0xe6, 0xe1, 0xc9, 0xd1, 0x5b, 0x7c, 0x11, 0x80, 0x25, 0x37, 0x8f, 0xa1, 0x38, 0xbc, 0x81, 0xfc,
	0x56, 0xca, 0xb0, 0x09, 0x8f, 0x76, 0x26, 0xc2, 0x31, 0xb3, 0xe3, 0x6d, 0x38, 0xa4, 0xb1, 0x7f,
	0x78, 0x0f, 0xe3, 0x9d, 0xeb, 0xf1, 0x2c, 0xfe, 0xf9, 0x5b, 0x27, 0x7f, 0xae, 0x79, 0xc9, 0x3c,
	0xbf, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x35, 0x86, 0xdd, 0xd6, 0x01, 0x00, 0x00,
}
